import type { DomainId } from '@/quiz/quiz.types';
import type { Locale } from '@/shared/i18n/locale';

/** A question generated by the edge function, or loaded back from
 * favorite_ai_questions once saved. Client-side id is `AI-<uuid>` until
 * favorited, after which it becomes the row's real Supabase uuid. */
export interface AiGeneratedQuestion {
  id: string;
  certId: string;
  domain: DomainId;
  m: 0 | 1;
  q: string;
  o: string[];
  a: number[];
  x: string;
  /** Which language q/o were generated in -- determines which column
   * `save()` writes into (question_en vs question_es). */
  questionLocale: Locale;
  /** Which language x was generated in -- independent of questionLocale,
   * matching the app's "questions in English, explanation in Spanish"
   * (or any other combination) flexibility. */
  explanationLocale: Locale;
  /** study_topics.id rows that grounded this question, for the "verify
   * this" link back to the study guide. */
  sourceTopicIds: string[];
}
