import type { DomainId } from '@/quiz/quiz.types';

/** A question generated by the edge function, or loaded back from
 * favorite_ai_questions once saved. Client-side id is `AI-<uuid>` until
 * favorited, after which it becomes the row's real Supabase uuid. */
export interface AiGeneratedQuestion {
  id: string;
  certId: string;
  domain: DomainId;
  m: 0 | 1;
  q: string;
  o: string[];
  a: number[];
  x: string;
  /** study_topics.id rows that grounded this question, for the "verify
   * this" link back to the study guide. */
  sourceTopicIds: string[];
}
